
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "leifdenby", email = "leif@denby.eu"},
]
dependencies = []
requires-python = ">=3.9"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
dev = [
    "pre-commit>=3.5.0",
]


[tool.isort]
profile = "black"
